runtime: go111

env: standard
service: snapshot
instance_class: F1
handlers:
  - url: /cron/snapshoting/.*
    script: auto
    login: admin

  - url: /cron/deleteing/.*
    script: auto
    login: admin

  - url: '/.*'
    script: auto

env_variables:
  PROJECT_ID: "<YOUR_PROJECT_ID>" # only work for localhost test
  DAYS_AGO: '7' # delete snapshots 7 days ago
